name: WakaTime Developer Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          INPUT_SHOW_TITLE: "true"
          INPUT_SHOW_TOTAL_CODE_TIME: "true"
          INPUT_SHOW_LANGUAGE: "true"
          INPUT_SHOW_EDITORS: "true"
          INPUT_SHOW_OS: "true"
          INPUT_SHOW_PROJECTS: "true"
          INPUT_SHOW_TIMEZONE: "true"
          INPUT_SHOW_COMMIT: "true"
          INPUT_SHOW_DAYS_OF_WEEK: "true"
          INPUT_SHOW_LANGUAGE_PER_REPO: "true"
          INPUT_SHOW_SHORT_INFO: "true"
          INPUT_SHOW_PROFILE_VIEWS: "false"
          INPUT_SHOW_UPDATED_DATE: "true"
